theme = "dark_plus"

# [editor.whitespace.render]
# space = "none"
# tab = "all"
# newline = "none"

[editor]
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"," = ["repeat_last_motion"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-f = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":redraw"] 
